# Generated by Django 3.1.3 on 2020-12-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Moja-apka'},
        ),
    ]
